// <auto-generated />
namespace undefined_shoes_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adddefaultgetDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddefaultgetDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202006020416581_add-default-getDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
